### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by dmlogic** [dmlogic/HelloWorld#1]
- [x] get .htaccess working for directing everything to php (rename on deploy)

- [x] get some unique reference on deploy and save it to a file (for cachebusting)

- [ ] Get shared storage working for logs and cache

- [x] Deal with .env vars. How to set on deploy without them being in git?

- [x] Write a .env file to work with above

- [ ] Spin up a DB server separately and connect to it with env vars

- [ ] Adjust the environment to be
    multi-server
    auto-patching

- [ ] Get a CRON working but only on the leading instance

- [ ] get HTTPS working. Self-signed-cert is fine

- [ ] Get the thing to auto-deploy when git is pushed
    BUT - are there occasions when we don't want to? Alternative is a cli-only based deploy which means certain laptops and ssh keys and things

- [ ] Put our app on it!

**Comment by dmlogic** [comment]
> .env vars. How to set on deploy without them being in git

Don't need to. Create a minimal hard-coded .env, set the rest via eb environment variables and dotenv will pick them up
